nginx:
  image: nginx:1.9.5
  ports:
    - "80:80"
    - "443:443"
  links:
    - php
    - memcached
  volumes:
    - ./app:/var/www/html/dev
    - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/logs:/var/log/nginx
memcached:
  image:  memcached
php:
  image: symfonyhhvm
  volumes:
    - ./app:/var/www/html/dev
    - ./server.ini:/etc/hhvm/server.ini
    - ./phpfpm-foreground:/usr/local/bin/phpfpm-foreground